using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations
{
    public partial class AddJobInvoices : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS job_invoices (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                    provider text NOT NULL,
                    external_invoice_id text NULL,
                    external_invoice_number text NULL,
                    external_status text NULL,
                    reference text NULL,
                    contact_name text NULL,
                    invoice_date date NULL,
                    line_amount_types text NOT NULL,
                    tenant_id text NULL,
                    request_payload_json text NULL,
                    response_payload_json text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_job_invoices_job_id
                    ON job_invoices(job_id);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS job_invoices;""");
        }
    }
}
