using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations
{
    public partial class AddCustomerServicePrices : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS service_catalog_items (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    service_type text NOT NULL,
                    category text NOT NULL,
                    name text NOT NULL,
                    personal_link_code text NULL,
                    dealership_link_code text NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    sort_order integer NOT NULL DEFAULT 0,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE INDEX IF NOT EXISTS ix_service_catalog_items_type_category
                    ON service_catalog_items(service_type, category);

                CREATE TABLE IF NOT EXISTS customer_service_prices (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id bigint NOT NULL,
                    service_catalog_item_id bigint NOT NULL,
                    xero_item_code text NOT NULL,
                    is_active boolean NOT NULL DEFAULT TRUE,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    CONSTRAINT "FK_customer_service_prices_customers_customer_id"
                        FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE,
                    CONSTRAINT "FK_customer_service_prices_service_catalog_items_service_catalog_item_id"
                        FOREIGN KEY (service_catalog_item_id) REFERENCES service_catalog_items (id) ON DELETE RESTRICT
                );

                CREATE INDEX IF NOT EXISTS ix_customer_service_prices_customer_id
                    ON customer_service_prices(customer_id);
                CREATE INDEX IF NOT EXISTS ix_customer_service_prices_service_catalog_item_id
                    ON customer_service_prices(service_catalog_item_id);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS customer_service_prices;""");
        }
    }
}
