using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations
{
    public partial class AddJobPayments : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS job_payments (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                    job_invoice_id bigint NOT NULL REFERENCES job_invoices(id) ON DELETE CASCADE,
                    provider text NOT NULL,
                    external_payment_id text NULL,
                    external_invoice_id text NULL,
                    method text NOT NULL,
                    amount numeric NOT NULL,
                    payment_date date NOT NULL,
                    reference text NULL,
                    account_code text NULL,
                    account_name text NULL,
                    external_status text NULL,
                    request_payload_json text NULL,
                    response_payload_json text NULL,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE INDEX IF NOT EXISTS ix_job_payments_job_id
                    ON job_payments(job_id);
                CREATE INDEX IF NOT EXISTS ix_job_payments_job_invoice_id
                    ON job_payments(job_invoice_id);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS job_payments;""");
        }
    }
}
