using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Workshop.Api.Migrations
{
    public partial class AddXeroTokenStore : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS xero_tokens (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    provider text NOT NULL,
                    refresh_token text NOT NULL,
                    access_token text NULL,
                    access_token_expires_at timestamptz NULL,
                    scope text NULL,
                    tenant_id text NULL,
                    tenant_name text NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    is_default boolean NOT NULL DEFAULT false,
                    created_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now()),
                    updated_at timestamptz NOT NULL DEFAULT date_trunc('milliseconds', now())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ux_xero_tokens_provider_tenant_id
                    ON xero_tokens(provider, tenant_id);
                CREATE INDEX IF NOT EXISTS ix_xero_tokens_is_default
                    ON xero_tokens(is_default);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS xero_tokens;""");
        }
    }
}
